[tools]
fzf = "latest"
yazi = "latest"
neovim = "latest"
pipx = "latest"
lua-language-server = "latest"
rust = "latest"
rust-analyzer = "latest"
lazygit = "latest"
typst = "latest"
tinymist = "latest"
resvg = "latest"
cargo-binstall = "latest"

[tasks.install_oh-my-zsh]
run = 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
description = "Install oh-my-zsh"

[tasks.install_oh-my-zsh_plugins]
run = [
	'git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions',
	'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions',
	'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting',
]
description = "Install oh-my-zsh plugins"

[tasks.install_pwndbg]
run = "curl --proto '=https' --tlsv1.2 -LsSf 'https://install.pwndbg.re' | sh -s -- -t pwndbg-gdb"
description = "Install pwndbg"

[tasks.install_tree-sitter-cli]
run = "cargo binstall tree-sitter-cli"
description = "Install Tree-sitter CLI"

